"""Spec-gap coverage: cloudinary parse, sapling blend, usage ledger,
TOC pagination, admin audit trail, per-model prompt rails."""
import json
import re


def test_cloudinary_parse_and_off_fallback(monkeypatch):
    from app.core.config import get_settings
    from app.services.storage.cloudinary_client import parse_cloudinary_url, upload_bytes

    key, secret, cloud = parse_cloudinary_url("cloudinary://k:s@mycloud")
    assert (key, secret, cloud) == ("k", "s", "mycloud")
    monkeypatch.setattr(get_settings(), "CLOUDINARY_URL", "")
    assert upload_bytes(b"data", public_id="x") is None  # no network touched


def test_sapling_blend_and_absent_key():
    from app.services.detector import _sapling_score, blend_with_sapling

    assert _sapling_score("anything") is None  # no key in test env
    assert blend_with_sapling(80.0, 0.2) == 80.0
    assert blend_with_sapling(60.0, 1.0) == 30.0


def test_usage_ledger_recorded(client, auth_headers):
    import uuid

    from app.repositories import document_repo
    from conftest import TestingSession

    made = client.post("/api/generate", headers=auth_headers,
                       json={"title": "Ledger", "idea": "Usage ledger idea check",
                             "doc_type": "rdd", "depth": "brief"})
    doc_id = made.json()["document_id"]
    me = client.get("/api/auth/me", headers=auth_headers).json()
    db = TestingSession()
    row = document_repo.get_owned(db, user_id=me["id"], document_id=doc_id)
    usage = json.loads(row.tokens_used_json)
    assert usage["completion_tokens"] > 0
    assert "llama" in usage["model"] or "nemotron" in usage["model"] or "mistral" in usage["model"]
    assert uuid.UUID(doc_id)  # opaque UUID, never sequential


def test_toc_pagination_exact():
    from app.services.exporter import build_print_html, paginate_sections

    sections = [
        {"title": "Alpha", "content_md": "Clear short sentence. " * 60},
        {"title": "Beta", "content_md": "Another one here. " * 10},
    ]
    pages, toc = paginate_sections(sections)
    assert toc[0] == {"title": "Alpha", "page": 1}
    assert toc[1]["page"] == len([p for p in pages]) and toc[1]["page"] > 1
    assert all(p["words"] <= 155 for p in pages)
    html = build_print_html(title="T", doc_type="rdd", sections=sections)
    assert "Contents" in html and "Alpha" in html
    assert "Page 2 /" not in html  # no fake running numbers, TOC carries exact sheets


def test_export_renders_markdown_and_escapes_xss():
    from app.services.exporter import build_docx, build_print_html, md_to_html

    sections = [{
        "title": "Sec <b>one</b>",
        "content_md": "## Sub head\n\n- **bold** item\n- plain item\n\n1. first step\n\n`code` here.",
        "content_humanized_md": "",
    }]
    html = build_print_html(title="T <i>x</i>", doc_type="rdd", sections=sections)
    assert "<b>one</b>" not in html and "&lt;b&gt;one&lt;/b&gt;" in html  # titles escaped
    assert "<strong>bold</strong>" in html and "<ul>" in html and "<ol>" in html
    assert "<code>code</code>" in html
    assert "##" not in html.split("Contents", 1)[-1]  # no raw markdown in body

    data = build_docx(title="T", sections=sections)
    assert data[:2] == b"PK"  # a real .docx zip, non-empty
    assert len(data) > 2000


def test_comprehensive_depth_delivers_20_sheets_and_latex_grade_pdf():
    from app.services import generator
    from app.services.exporter import build_print_html, paginate_sections

    assert generator._target_words("comprehensive") == "900-1200"
    sections = generator._mock_sections("Demo Title", "rdd", "comprehensive")
    assert len(sections) == 7  # full outline, not a 4-section stub
    total = sum(s["word_count"] for s in sections)
    assert total >= 6000  # ≈20 printed A4 pages at ~350 words/page
    pages, _toc = paginate_sections(sections)
    assert len(pages) >= 20
    html = build_print_html(title='Demo "Quoted" Title', doc_type="rdd", sections=sections)
    assert "Latin Modern" in html  # LaTeX-grade serif stack
    assert "counter(page)" in html and "@top-center" in html  # engine-computed numbers
    assert 'class=\'rule\'' in html  # ruled title page
    running_head = html.split("@top-center")[1].split("content:")[1].split(";")[0]
    assert running_head.count('"') == 2  # exactly the wrapping pair: title quotes stripped
    assert "Page 2 /" not in html  # still no hardcoded numbers


def test_export_tex_is_compilable_source():
    from app.services.exporter import build_tex

    sections = [{
        "title": "Goals & Plans",
        "content_md": "Hit **100%** of $targets$ — see `run()` #tag.\n\n- first\n- second\n\n```mermaid\ngraph TD\n  A-->B\n```",
        "content_humanized_md": "",
    }]
    tex = build_tex(title="R&D 100%", doc_type="rdd", sections=sections)
    assert tex.startswith("% Generated by DocuForge")
    assert "\\documentclass" in tex and "\\tableofcontents" in tex
    assert "\\section{Goals \\& Plans}" in tex  # escaped
    assert "\\textbf{100\\%}" in tex and "\\$targets\\$" in tex  # escaped inline
    assert "\\begin{itemize}" in tex
    assert "\\begin{verbatim}\n" in tex and "graph TD" in tex  # diagram appendix
    assert "\\end{document}" in tex
    # Balanced braces outside verbatim (pdflatex would choke otherwise).
    body = re.sub(r"\\begin\{verbatim\}.*?\\end\{verbatim\}", "", tex, flags=re.DOTALL)
    assert body.count("{") == body.count("}")


def test_per_section_generation_and_comprehensive_depth(client, auth_headers, monkeypatch):
    """Real (non-mock) path: one LLM call per outline section, 7 sections out."""
    import re as _re

    from app.services import generator
    from app.services.llm import nim_client

    calls = []

    async def fake_section_post(model, messages, max_tokens, transport=None):
        calls.append((model, messages[-1]["content"], max_tokens))
        n = len(calls)
        return f"Body text for section number {n} with enough words to count here now."

    class _LiveSettings:
        NIM_MOCK = False
        NVIDIA_NIM_API_KEY = "server-key"
        LLM_KEYS_SECRET = ""
        JWT_SECRET = "test-secret-for-pytest-only"

    monkeypatch.setattr(nim_client, "_post", fake_section_post)
    monkeypatch.setattr(nim_client, "get_settings", lambda: _LiveSettings())
    import app.services.keys as _keys
    monkeypatch.setattr(_keys, "get_settings", lambda: _LiveSettings())

    # Admin so the key-ownership gate doesn't interfere.
    from app.core.security import hash_password
    from app.repositories import user_repo
    from conftest import TestingSession
    db = TestingSession()
    admin = user_repo.create(db, email="sections-admin@example.com",
                             password_hash=hash_password("adminpass123"),
                             display_name="S")
    user_repo.set_role(db, admin, "admin")
    db.close()
    login = client.post("/api/auth/login",
                        json={"email": "sections-admin@example.com", "password": "adminpass123"})
    headers = {"Authorization": f"Bearer {login.json()['access_token']}"}

    resp = client.post("/api/generate", headers=headers,
                       json={"title": "Long Doc", "idea": "A comprehensive manual idea here",
                             "doc_type": "rdd", "depth": "comprehensive"})
    assert resp.status_code == 200, resp.text
    assert len(resp.json()["sections"]) == 7  # full RDD outline, one call each
    assert len(calls) == 7
    assert all("Write ONLY the section" in prompt for _, prompt, _ in calls)
    assert all(budget >= 1400 for _, _, budget in calls)  # comprehensive budgets


def test_admin_audit_trail(client):
    from app.core.security import hash_password
    from app.entities.admin_audit import AdminAudit
    from app.repositories import user_repo
    from conftest import TestingSession

    db = TestingSession()
    admin = user_repo.create(db, email="audit-admin@example.com",
                             password_hash=hash_password("adminpass123"),
                             display_name="A")
    target = user_repo.create(db, email="audit-user@example.com",
                              password_hash=hash_password("userpass123"),
                              display_name="U")
    user_repo.set_role(db, admin, "admin")
    token = client.post("/api/auth/login",
                        json={"email": "audit-admin@example.com",
                              "password": "adminpass123"}).json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}
    resp = client.put(f"/api/admin/users/{target.id}/role",
                      headers=headers, json={"role": "admin"})
    assert resp.status_code == 200
    trail = db.query(AdminAudit).filter(AdminAudit.target_id == target.id).all()
    assert len(trail) == 1 and trail[0].old_role == "user" and trail[0].new_role == "admin"
    stats = client.get("/api/admin/stats", headers=headers).json()
    assert "recent_audits" in stats and "tokens_by_model" in stats


def test_per_model_prompt_rails():
    from app.services.llm.models import humanize_suffix

    assert "20 words" in humanize_suffix("mistralai/mistral-7b-instruct-v0.3")
    assert humanize_suffix("mistralai/mistral-large-2-instruct") == ""


def test_meta_detector_shape(client, auth_headers):
    detector = client.get("/api/meta/models", headers=auth_headers).json()["detector"]
    assert {"mode", "analyzer", "demo_mode", "sapling"} <= set(detector)
