"""150 words/page engine: sentence-greedy pagination (code/diagrams excluded)
+ print-CSS HTML builder for the MVP client-print path."""
import re

from app.services.detector import _sentences, count_words

WORDS_PER_PAGE = 150
TOLERANCE = 5


def _body_text(markdown: str) -> str:
    no_code = re.sub(r"```.*?```", "", markdown, flags=re.DOTALL)
    return re.sub(r"^#{1,6}\s+.*$", "", no_code, flags=re.MULTILINE)


def paginate(sections: list[dict]) -> list[dict]:
    """Greedy sentence packing to ~150 words/page; merge-forward if last <100."""
    pages: list[dict] = []
    current: list[str] = []
    current_words = 0

    def flush():
        nonlocal current, current_words
        if current:
            pages.append({"words": current_words, "sentences": current})
            current, current_words = [], 0

    for section in sections:
        text = section.get("content_humanized_md") or section.get("content_md", "")
        for sent in _sentences(_body_text(text)):
            w = count_words(sent)
            if current_words + w > WORDS_PER_PAGE + TOLERANCE and current:
                flush()
            current.append(sent)
            current_words += w
    flush()
    if len(pages) > 1 and pages[-1]["words"] < 100:
        last = pages.pop()
        pages[-1]["sentences"].extend(last["sentences"])
        pages[-1]["words"] += last["words"]
    return pages


def build_print_html(*, title: str, doc_type: str, sections: list[dict]) -> str:
    pages = paginate(sections)
    body_pages = "".join(
        f"<section class='page'><p>{' '.join(p['sentences'])}</p>"
        f"<footer>Page {i + 1} / {len(pages)}</footer></section>"
        for i, p in enumerate(pages)
    )
    return f"""<!DOCTYPE html><html><head><meta charset='utf-8'><title>{title}</title>
<style>
@page {{ size: A4; margin: 2.5cm 2cm; @bottom-center {{ content: counter(page) ' / ' counter(pages); }} }}
body {{ font-family: Inter, sans-serif; font-size: 11pt; line-height: 1.6; }}
h1 {{ font-family: Newsreader, serif; }}
.page {{ page-break-after: always; }}
footer {{ text-align: center; color: #6B7280; font-size: 9pt; }}
</style></head><body>
<section class='page'><h1>{title}</h1><p>{doc_type} — generated by DocuForge</p></section>
{body_pages}
</body></html>"""


def build_docx(*, title: str, sections: list[dict]) -> bytes:
    from io import BytesIO

    from docx import Document as DocxDocument

    doc = DocxDocument()
    doc.add_heading(title, level=0)
    for section in sections:
        doc.add_heading(section.get("title", ""), level=1)
        doc.add_paragraph(section.get("content_humanized_md") or section.get("content_md", ""))
    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
