"""Machine-readable error codes. Every API error returns
{"code": <one of these>, "message": <humanized copy>} so clients can
branch on `code` while humans read `message`."""

# --- auth ---
AUTH_REQUIRED = "AUTH_REQUIRED"
AUTH_EXPIRED = "AUTH_EXPIRED"
AUTH_BAD_CREDENTIALS = "AUTH_BAD_CREDENTIALS"
AUTH_FORBIDDEN_ADMIN = "AUTH_FORBIDDEN_ADMIN"
AUTH_EMAIL_TAKEN = "AUTH_EMAIL_TAKEN"
AUTH_BAD_REFRESH = "AUTH_BAD_REFRESH"
AUTH_BAD_RESET = "AUTH_BAD_RESET"
AUTH_NO_ACCOUNT = "AUTH_NO_ACCOUNT"

# --- resources ---
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
PROJECT_TITLE_REQUIRED = "PROJECT_TITLE_REQUIRED"
DOC_NOT_FOUND = "DOC_NOT_FOUND"
SECTION_NOT_FOUND = "SECTION_NOT_FOUND"
VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
EXPORT_NOT_FOUND = "EXPORT_NOT_FOUND"
EXPORT_FILE_GONE = "EXPORT_FILE_GONE"
TEMPLATE_UNKNOWN = "TEMPLATE_UNKNOWN"
ROLE_INVALID = "ROLE_INVALID"
SECTION_BAD_MOVE = "SECTION_BAD_MOVE"

# --- models / AI ---
MODEL_NOT_ALLOWED = "MODEL_NOT_ALLOWED"
MODEL_EMPTY_RESPONSE = "MODEL_EMPTY_RESPONSE"
MODEL_TOO_LONG = "MODEL_TOO_LONG"
MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
BYOK_INVALID = "BYOK_INVALID"
BYOK_NOT_FOUND = "BYOK_NOT_FOUND"

# --- platform ---
DB_NOT_CONFIGURED = "DB_NOT_CONFIGURED"
RAG_NOT_CONFIGURED = "RAG_NOT_CONFIGURED"
RAG_EMPTY_QUERY = "RAG_EMPTY_QUERY"
RAG_BAD_TOP_K = "RAG_BAD_TOP_K"
RAG_EMBED_FAILED = "RAG_EMBED_FAILED"
